### ISSUE TITLE
Error parsing script client.lua

### ISSUE THREAD

**Issue by avilchiis** [LuaDeldu/esx_yellowjackjob#1]
I'm having this error on console

Error parsing script @esx_yellowjack/client.main.lua in resource esx_yellowjack: @esx_yellowjack/client/main.lua:670: 'then' expected near '='

All I did was drag and drop the script, nothing changed in code

**Comment by delduwaht** [comment]
Fixed with 7f208b98d52fc1b451a58614fbbf284af1f0124a
